name: Merge Updates

run-name: Removing traces of the pull request repo from the merge

# only when pull requests are closed
on:
  pull_request:
    types:
      - closed

jobs:
  update_gomod: # only run once the repo has been merged
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, Linux]
    steps:
    # checkout downloads the latest checkout of the repo
    # means pushed updates are included in the scripts etc
    - uses: actions/checkout@v3
    - run: chmod u+x ./clogrc/replacepush.sh
    # run the destination folder, the current repo, the target repo and the pat to push all the updates
    - run: ./clogrc/replacepush.sh . ${{ github.event.pull_request.head.repo.full_name }} ${{ github.actor }}/${{ github.event.repository.name }} ${{ secrets.PAT }}
